Desktop versions
lolashot/e-learning-platform pull request #2
Opened 2022-09-15 20:40 UTC by lolashot

2022-09-15 23:58 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @lolashot 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- [ ] You did great by implementing your own design in the mobile version it looks nice but makes sure your design fits the provided  design as much as possible :smile: :smile: :smile: 
- [ ] For the desktop version you did a great job, your design is nicely done but just change your background image and I list some few points below :smile: :smile: :smile: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-15 23:58 UTC, MaganaAsiati commented on about.html
> +      </div>
- [ ] Kindly make sure all pictures are displaying properly on your page, cause as you see in the picture below there are two images that are not displaying fix that, please  so that it will make your design look nice :smiley: 

![image](https://user-images.githubusercontent.com/95297251/190523425-de69e1ee-0e78-4ab0-8fe1-26f175396706.png)

2022-09-15 23:58 UTC, MaganaAsiati commented on style.css
> +    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.05);
- Kindly make sure your mobile version design fits the provided design, I  provide the link below and some pictures that will guide you. they represent your design compared to the provided design . Here is the [link](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) to the provided design.

## Provide mobile menu design
  1. It contains a hamburger menu on the left side.
  2. Its background is transparent or the same color/pattern as the top section background.

![image](https://user-images.githubusercontent.com/95297251/190525325-3dfc94dd-cd1e-4ad6-8ba2-fc13d6a07736.png)

## Your mobile menu design

![image](https://user-images.githubusercontent.com/95297251/190525458-70d2590e-17b1-41b5-ace9-efa9f5c0e12b.png)

2022-09-15 23:58 UTC, MaganaAsiati commented on about.html
> +
- Kindly make your footer match to the provide design as it explain bellow 

##### Footer

1. It contains a logo aligned to the left and text aligned to the right.

###### Mobile Size

1. It has a white background.

###### Desktop Size

1. About Page: It has a dark background.
1. Home Page: It has a white background.

2022-09-15 23:58 UTC, MaganaAsiati commented on about.html
> +      </div>
- [ ] Kindly make sure the card section is correctly arranged, and make your design fit the provided design which shows below 
- [ ] kindly make sure you add this button to see more picture  as it shows in the design


![image](https://user-images.githubusercontent.com/95297251/190526818-ba0c665d-3b85-4fe6-b112-bec9d474697b.png)

2022-09-15 23:58 UTC, MaganaAsiati commented on style.css
> +}
- Kindly make sure that you use the same background as it shows in the provided design take a look in the picture below and implement it, please.

![image](https://user-images.githubusercontent.com/95297251/190527787-be6c962a-7940-406c-9328-1879fe81e581.png)

2022-09-16 14:12 UTC, whiz25 commented on style.css
> +    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.05);
![Screenshot_20220916-161142_Chrome](https://user-images.githubusercontent.com/19773024/190659295-464c4b2a-c378-49c5-8707-00a3f72a1ad4.jpg)
- Make sure the menu looks like the one in the design. Please fix that change.

2022-09-16 14:17 UTC, whiz25 commented on about.html
> +      </div>
This section of your design still needs work 
![Screenshot_20220916-161657_Chrome](https://user-images.githubusercontent.com/19773024/190660500-0186fe75-e382-42c7-9f79-b9b11701d729.jpg)

2022-09-16 14:18 UTC, whiz25 commented on index.html
> +            <li><a href="#courses" class="toggler">courses</a></li>
- Please update your design accordingly. You didn't follow the provided design
![Screenshot_20220916-161808_Chrome](https://user-images.githubusercontent.com/19773024/190660858-cff17925-4448-4c33-a26f-d138391eca87.jpg)

2022-09-16 14:20 UTC, whiz25 requested changes
Hi @lolashot, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🎉 🎉 🎉 
- Made some requested changes

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 14:37 UTC, lolashot commented
hi @whiz25 
you didn't mention the changes you want me to make

2022-09-16 19:26 UTC, codecaiine requested changes
Hi @lolashot , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes

- [ ] [OPTIONAL] Please make sure that you follow the original design as required for this project I noticed a few differences between your design and the original one. As a developer, it is very important to pay attention to details to give the best user experience, make your website as expected, and also because your future employer will judge you on that. :smile: 
 
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-16 19:26 UTC, codecaiine commented on about.html
> +      </header>
- [ ] [REQUIRED] Good job so far working on changes :+1: But your mobile menu is a bit different from the original design :cry: As the previous reviewer mentioned you need to make sure that the menu looks like the one in the design to make your website wonderful and give to user good attention.  As a developer, you need to pay attention to details. Please fix the menu for both index.html and about.html pages :+1: 
Please check the screenshots below to see the difference :arrow_down: 

#### Your design
![Screenshot from 2022-09-16 18-54-32](https://user-images.githubusercontent.com/6615394/190712027-d6c7ead5-680d-4e09-a09d-4f5210b27232.jpg)

#### Original design
![Screenshot from 2022-09-16 18-54-59](https://user-images.githubusercontent.com/6615394/190712031-3a44ecd1-ebf3-4e84-aaee-8864eac4e405.png)

2022-09-16 19:26 UTC, codecaiine commented on index.html
> +                 </div>
- [ ] [REQUIRED] The different previous reviewers pointed out this section and you made a great effort with the lecturer section design :clap: But you need to need work on and make it similar to the original design there is a few difference. Please fix it in order to make your website works and be beautiful and it is important to pay attention to details :+1: 

#### Original design
![Screenshot from 2022-09-16 19-01-56](https://user-images.githubusercontent.com/6615394/190713336-f6114461-1095-4b1f-91b2-3108ba5fe447.png)

#### Your design
![Screenshot from 2022-09-16 19-01-35](https://user-images.githubusercontent.com/6615394/190713344-07912e2f-9dfc-4d98-a461-c8d79b27e239.png)

2022-09-16 19:26 UTC, codecaiine commented on index.html
> +          </div>
- [ ] [REQUIRED] Good job so far :clap: But as the previous reviewer mentioned above you need to follow the original design :smile: Please make sure that your design matches the original design as required for this project :+1: 
You can check the screenshots below :arrow_down: to see the differences :smile: 

#### Your design
![Screenshot from 2022-09-16 19-12-14](https://user-images.githubusercontent.com/6615394/190714932-14a2dab6-bf70-4b64-8ff7-eae362fbb05d.png)

#### The original design
![Screenshot from 2022-09-16 19-01-56](https://user-images.githubusercontent.com/6615394/190714938-dbe17893-0412-4f5c-afd9-0d598bc254d1.png)

2022-09-17 07:00 UTC, mgmediaweb commented on index.html
> +            <li><a href="#courses" class="toggler">courses</a></li>
Kindly, I suggest you follow the instructions of the previous reviewer, in this case each item in the list contains a mouse over effect (white border) that is currently not implemented on your site, please make the corresponding changes

2022-09-17 07:01 UTC, mgmediaweb commented on about.html
> +      </div>
Good job following the advice of the previous reviewer

2022-09-17 07:05 UTC, mgmediaweb commented on about.html
> +      </div>
![image](https://user-images.githubusercontent.com/41912912/190844988-693bb220-cfd2-4873-b0a8-95ee97bf896c.png)
Kindly, currently your website in mobile version does not look good, the images are not proportionally reduced, in addition to the "show more" button is not working as it should

2022-09-17 07:07 UTC, mgmediaweb commented on style.css
> +}
Kindly, this section does not look like the original design, you should use the "cocogoose" font for the titles

2022-09-17 07:09 UTC, mgmediaweb requested changes
Hi @lolashot , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![work3](https://user-images.githubusercontent.com/41912912/190845110-54d3db6c-55c0-4368-a708-80d4bf88a3d6.gif)


 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 16:26 UTC, emmiiorji commented on index.html
> +            <li><a href="#courses" class="toggler">courses</a></li>
Kindly stick to the design just as the previous reviewers have recommended. Your background is different from that of the design. One way you can achieve the background is copying a square area on the background and letting it repeat.

Your current design:
![image](https://user-images.githubusercontent.com/20554583/190866715-b6879b7f-b682-4803-8633-ab6b30ae2c36.png)

Guidelines design:
![guideline](https://user-images.githubusercontent.com/95297251/190521788-d0bbc5f2-aaee-4885-b0e0-55e6888a3128.png)

2022-09-17 16:37 UTC, emmiiorji requested changes
Hi @lolashot, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost there](https://user-images.githubusercontent.com/20554583/190865853-ca780fc9-30cc-410c-b367-4806a8fec3df.gif)


 ## Good Highlights ✔

- PR is descriptive
- Some requested changes have been implemented


 ## Required Changes ♻️

- Your design seems to fundamentally differ from the given design guideline. It'll be a good habit right now to follow given designs as closely as possible. This will help you in preparation for a typical work place experience where you might be required to reproduce a given design to the later.

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 16:37 UTC, emmiiorji commented on index.html
> +            <li><a href="#courses" class="toggler">courses</a></li>
Kindly stick to the design just as the previous reviewers have recommended. Your background is different from that of the design. One way you can achieve the background is copying a square area on the background and letting it repeat.

Your current design:
![image](https://user-images.githubusercontent.com/20554583/190866715-b6879b7f-b682-4803-8633-ab6b30ae2c36.png)

Guidelines design:
![guideline](https://user-images.githubusercontent.com/95297251/190521788-d0bbc5f2-aaee-4885-b0e0-55e6888a3128.png)

2022-09-17 16:37 UTC, emmiiorji commented on index.html
> +                      <hr class="desktopline w-50">
As recommended by the previous reviewer, kindly make this section match the design.

Your design
![image](https://user-images.githubusercontent.com/20554583/190866900-3d3c0908-987a-4851-859f-b5f0c7ee31a6.png)


Design guideline:
![image](https://user-images.githubusercontent.com/20554583/190866986-6d1c1518-500c-444a-9106-0b3d65b68d6d.png)

2022-09-17 16:37 UTC, emmiiorji commented on index.html
> +                <h4 class="text2 grey">So lets start learning web development.</h4>
As recommended by previous reviewer, kindly make the hero section match the design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/190867108-b4abffa2-c428-497d-8524-fe418ddfef75.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/190867131-295a8952-e7bf-407e-91f8-60c9f48224d2.png)

2022-09-17 18:51 UTC, Lameck1 reviewed
Hello @lolashot 👋,

_This is an additional review as a result of the second opinion request._

Let's discuss your concern. Please take a look at the screenshot below:


  | ![Screenshot 2022-09-17 213526](https://user-images.githubusercontent.com/45002654/190871781-389b1182-26d8-42ca-9c8e-19c6b93f3dff.png) |
  | --- |

You are free to personalize the content of your page. Small adjustments like text or image changes are acceptable. But, taking a look at the requirement circled in red, the design guideline should be followed. Changes requested are based on color, typography, and layout. Please ensure that these aspects are matching the design.

Be encouraged to work on the required changes and then ask for another review.

Keep rocking 🚀!

2022-09-17 19:48 UTC, Ismailco requested changes
#### Hi @lolashot, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-17 19:48 UTC, Ismailco commented on index.html
> +              </div>
- [ ] As recommended by the previous reviewer, kindly make the hero section match the design, Your design needs to be exactly like the Original design, and the background should respect the accesibility rules as the provided design, it would be helpful to add an overlay over the image so the text is more clear, and the paragraph should have a border

|Your design|CC design|
|-|-|
|![Screenshot_20220917_204638](https://user-images.githubusercontent.com/25227022/190874101-cb09a40b-2e25-4253-8fcb-d9128f33d471.png)|![image](https://user-images.githubusercontent.com/25227022/190874089-e852af75-ced3-4a62-90fd-716c8bb2908a.png)|

2022-09-19 19:53 UTC, cynthiainga requested changes
Hi @lolashot, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +              <button class="btn btn-outline-secondary" disabled type="button">MORE
- [ ] I noticed that you decide to add this button but it not working, as it's an additional requirement if you decide to add this button you should make sure that it works correctly it means that when the user clicks the more button user can see all the lectures and the button change to the `LESS` and if the user clicks to the `LESS` button the user can see only two lectures and the button change to `MORE again, this is the functionality of this button. Please kindly fix that 🙃 😉

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +      <!-- </div> -->
- [ ] Please kindly delete the comments lines of code to have a clean and professional codebase 😎

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +        </ul>
- [ ] I think it should be better if you put your navigation part in the `nav` tag for good practice of semantics tags 😉 😉

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +      <header>
- [ ] To the top of the page there is a top short bar section with social media links, logout, and language links aligned to the right. I noticed that you don't have this part on your design please kindly add that part 🙃 🙃 

Your design

<img width="1019" alt="Screen Shot 2022-09-19 at 21 24 20" src="https://user-images.githubusercontent.com/74501523/191099013-cdf15c4e-5803-418f-be6d-7ed001f38e46.png">

Provided design 

<img width="885" alt="Screen Shot 2022-09-19 at 21 23 43" src="https://user-images.githubusercontent.com/74501523/191099110-144ed0e5-1271-4bfb-9078-ee08f59c991b.png">

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +        <a href="#" class="logo">RICHES</a>
- [ ] As mentioned in the project requirements the logo in the header links to the home page, which means if, for example, I navigate to the about page and click on the logo it directs me to the home page automatically. So please kindly links your logo to the home page 🙃 😉

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +              <h3 class="greeting">hi There,</h3>
- [OPTIONAL] I suggest you begin your salutation with a capital letter 😉

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +                    </h4>
- [ ] For best practice of `HTML` I suggest you change this in a paragraph tag, is a paragraph and not a title 🙃 🙃

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +                <h4 class="text2 grey">So lets start learning web development.</h4>
- [ ] Same remark about best practices of `HTML`, kindly change those two title in paragraph  😉

2022-09-19 19:53 UTC, cynthiainga commented on index.html
> +                  <h6 class="col-6 m-auto texter">learn and become a world class frontend developer with our popular frontend frameworks.</h6>
- [ ] I think it should be better if you use the first tag the `hx` tag and the second the `p` tag, I think you made the confusion, the first one is the title and the second one is the paragraph. Please make sure to change it for all your courses 🙃 🙃

2022-09-22 05:03 UTC, mgmediaweb requested changes
Hi @lolashot , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost5](https://user-images.githubusercontent.com/41912912/191662156-6fdc0b4e-8958-4b20-beb4-973fb4fc2d5b.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 
- I appreciate your effort, you can do it! ✔️ 

 ## Required Changes ♻️

Kindly, I suggest you review this horizontal scrooll that prevents your site from looking good, find the element that is producing it and adjust it, there is very little left to finish, you can do it!

![image](https://user-images.githubusercontent.com/41912912/191662103-7e7289d2-ee87-488e-8397-8b08b17a87b9.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:35 UTC, omarsalem7 approved these changes
Hi @lolashot 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 05:37 UTC, merged